# Generated by Django 5.1.2 on 2024-11-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0007_auto_20200325_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Send_Feedback',
        ),
    ]
